Repository Alzheimer-dinger/FE, pull requests merged in 2025-08, with the labels that each got.

#17 [통화] 통화화면 UI 구현
  src/App.tsx
  src/components/CallBtn.tsx
  src/components/RecordCard.tsx
  src/components/VoiceWave.tsx
  src/components/common/Header/DefaultHeader.tsx
  src/components/common/Header/SearchHeader.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/constants/dummy.ts
  src/hooks/useAudioStream.ts
  src/pages/Call.tsx
  src/pages/call/Call.tsx
  src/pages/call/CallActive.tsx
  src/pages/call/CallWaiting.tsx
  src/pages/call/RecordDetail.tsx
  src/pages/index.ts
  src/pages/init/Login.tsx
  src/pages/init/Signup.tsx
  src/pages/init/SignupRole.tsx
  src/pages/init/SignupTerms.tsx
  src/utils/calldate.ts
  src/utils/formatDateTime.ts
Labels: ✨ Feat

#18 [리포트, 마이페이지] 리포트,마이페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/BudgetLine.tsx
  src/components/CalendarEmojis.tsx
  src/components/EmotionLineChart.tsx
  src/components/EmotionScoreCircle.tsx
  src/components/PatientCard.tsx
  src/components/SettingItem.tsx
  src/components/TabMenu.tsx
  src/components/common/BottomNav.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/modal/AddPatientModal.tsx
  src/components/modal/ConfirmActionModal.tsx
  src/components/modal/FeedbackModal.tsx
  src/components/modal/LogoutModal.tsx
  src/components/modal/ProfileImageModal.tsx
  src/components/modal/TimePickerModal.tsx
  src/components/modal/index.ts
  src/pages/Mypage.tsx
  src/pages/Report.tsx
  src/pages/index.ts
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/PatientGuardianManage.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/report/DailySection.tsx
  src/pages/report/Report.tsx
  src/pages/report/TotalSection.tsx
Labels: ✨ Feat

#19 [배포] 통화, 리포트, 마이페이지 main 배포
  package-lock.json
  package.json
  src/App.tsx
  src/components/BudgetLine.tsx
  src/components/CalendarEmojis.tsx
  src/components/CallBtn.tsx
  src/components/EmotionLineChart.tsx
  src/components/EmotionScoreCircle.tsx
  src/components/PatientCard.tsx
  src/components/RecordCard.tsx
  src/components/SettingItem.tsx
  src/components/TabMenu.tsx
  src/components/VoiceWave.tsx
  src/components/common/BottomNav.tsx
  src/components/common/Header/DefaultHeader.tsx
  src/components/common/Header/SearchHeader.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/modal/AddPatientModal.tsx
  src/components/modal/ConfirmActionModal.tsx
  src/components/modal/FeedbackModal.tsx
  src/components/modal/LogoutModal.tsx
  src/components/modal/ProfileImageModal.tsx
  src/components/modal/TimePickerModal.tsx
  src/components/modal/index.ts
  src/constants/dummy.ts
  src/hooks/useAudioStream.ts
  src/pages/Call.tsx
  src/pages/Mypage.tsx
  src/pages/Report.tsx
  src/pages/call/Call.tsx
  src/pages/call/CallActive.tsx
  src/pages/call/CallWaiting.tsx
  src/pages/call/RecordDetail.tsx
  src/pages/index.ts
  src/pages/init/Login.tsx
  src/pages/init/Signup.tsx
  src/pages/init/SignupRole.tsx
  src/pages/init/SignupTerms.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/PatientGuardianManage.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/report/DailySection.tsx
  src/pages/report/Report.tsx
  src/pages/report/TotalSection.tsx
  src/utils/calldate.ts
  src/utils/formatDateTime.ts
Labels: 🌏 Merge

#22 [배포] 디자인 수정
  src/components/SettingItem.tsx
  src/components/TabMenu.tsx
  src/components/common/Input.tsx
  src/components/modal/AddPatientModal.tsx
  src/components/modal/ConfirmActionModal.tsx
  src/components/modal/FeedbackModal.tsx
  src/components/modal/LogoutModal.tsx
  src/components/modal/ProfileImageModal.tsx
  src/components/modal/TimePickerModal.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/PatientGuardianManage.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/report/Report.tsx
  src/pages/report/TotalSection.tsx
Labels: 🌏 Merge

#32 Feat/#28/리포트 api 기능 추가
  cors.json
  src/components/BudgetLine.tsx
  src/components/CalendarEmojis.tsx
  src/components/EmotionScoreCircle.tsx
  src/components/TabMenu.tsx
  src/components/index.ts
  src/components/modal/FeedbackModal.tsx
  src/components/modal/ProfileImageModal.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/PatientGuardianManage.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/report/DailySection.tsx
  src/pages/report/Report.tsx
  src/pages/report/TotalSection.tsx
  src/services/api.ts
Labels: 📬 API, ✨ Feat

#34 [배포] api 연동
  cors.json
  src/App.tsx
  src/components/BudgetLine.tsx
  src/components/CalendarEmojis.tsx
  src/components/EmotionScoreCircle.tsx
  src/components/RecordCard.tsx
  src/components/TabMenu.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/modal/FeedbackModal.tsx
  src/components/modal/ProfileImageModal.tsx
  src/hooks/useAudioStream.ts
  src/hooks/useFCM.ts
  src/main.tsx
  src/pages/call/Call.tsx
  src/pages/call/CallActive.tsx
  src/pages/call/RecordDetail.tsx
  src/pages/init/Login.tsx
  src/pages/init/Signup.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/PatientGuardianManage.tsx
  src/pages/mypage/ProfileEdit.tsx
  src/pages/report/DailySection.tsx
  src/pages/report/Report.tsx
  src/pages/report/TotalSection.tsx
  src/services/api.ts
  src/services/gemini-client.ts
  src/utils/auth.ts
  src/utils/calldate.ts
  src/utils/setupFetchInterceptor.ts
Labels: 🌏 Merge

#48 [배포] 통화 api 및 형식 수정
  package-lock.json
  package.json
  src/components/RecordCard.tsx
  src/pages/Loading.tsx
  src/pages/call/Call.tsx
  src/pages/call/CallWaiting.tsx
  src/pages/call/RecordDetail.tsx
  src/pages/index.ts
  src/services/apiService.ts
  src/utils/calldate.ts
Labels: 🌏 Merge

#52 [배포] 리포트,마이페이지 api 연결 오류 해결
  public/manifest.json
  src/pages/mypage/Mypage.tsx
  src/pages/report/DailySection.tsx
  src/pages/report/Report.tsx
  src/services/api.ts
  src/utils/setupFetchInterceptor.ts
Labels: 🌏 Merge

#60 [배포] 통화 시간 format 수정
  src/components/CalendarEmojis.tsx
  src/components/RecordCard.tsx
  src/components/SettingItem.tsx
  src/components/TabMenu.tsx
  src/components/modal/ProfileImageModal.tsx
  src/pages/mypage/PatientGuardianManage.tsx
  src/pages/report/DailySection.tsx
  src/pages/report/Report.tsx
  src/pages/report/TotalSection.tsx
  src/services/api.ts
  src/utils/calldate.ts
  src/utils/setupFetchInterceptor.ts
Labels: 🌏 Merge

#62 [배포] 관계 이미지 기능 추가
  src/pages/mypage/PatientGuardianManage.tsx
  src/pages/report/Report.tsx
  src/services/api.ts
Labels: 🌏 Merge
